---
apiVersion: v1
kind: Service
metadata:
  name: storage-{{ .Values.loader.name }}-{{ .Values.loader.type }}
  namespace: ns-{{ .Values.loader.name }}-{{ .Values.loader.type }}
spec:
  type: ExternalName
  externalName: {{ .Values.storage.host }}

---
apiVersion: v1
kind: Service
metadata:
  name: amqp-{{ .Values.loader.name }}-{{ .Values.loader.type }}
  namespace: ns-{{ .Values.loader.name }}-{{ .Values.loader.type }}
spec:
  type: ExternalName
  externalName: {{ .Values.amqp.host }}

